### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by mingjenglee** [mingjenglee/mj-toys#6]
2016-08-23 09:14:57, add 10 new faults.
Traceback (most recent call last):
  File "update.py", line 220, in <module>
    fetchAndUpdateData(src)
  File "update.py", line 106, in fetchAndUpdateData
    fdom = parseString(doc)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1930, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

C:\all2\www\faultchartdocs>min

**Comment by mingjenglee** [comment]
Happened again on 8/26 14:34:05.

**Comment by mingjenglee** [comment]
This fixed on 8/29.
